name: Release
on: 
  workflow_dispatch:
    inputs:
      skip-tests:
        description: Skip tests
        required: false
        type: boolean
        default: false

  workflow_call:
    inputs:
      skip-tests:
        description: Skip tests
        required: false
        type: boolean
        default: false

env:
  repository: podium
  role: ${{ secrets.role }}
  region: ${{ secrets.registy_region }}

jobs:
  test:
    if: ${{ !inputs.skip-tests }}
    uses: ./.github/workflows/test.yml
    secrets: inherit
  
  build:
    needs: [test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & publish Docker image
        uses: ./.github/actions/build
        with:
          repository: ${{ env.repository }}
          role: ${{ env.role }}
          region: ${{ env.region }}
