name: Test
on: 
  push:
    branches:
      - master
  pull_request:
  workflow_call:

env:
  go-version: 1.20

jobs:
  standalone:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:4
        options: '--health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5'
        ports:
          - '6379:6379'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Redis cluster
        uses: vishnudxb/redis-cluster@1.0.5
        with:
          master1-port: 5000
          master2-port: 5001
          master3-port: 5002
          slave1-port: 5003
          slave2-port: 5004
          slave3-port: 5005

      - name: Test
        uses: ./.github/actions/test
        id: standalone
        with:
          cluster-mode: false
          go-version: ${{ inputs.go-version }}

  cluster:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:4
        options: '--health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5'
        ports:
          - '6379:6379'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Redis cluster
        uses: vishnudxb/redis-cluster@1.0.5
        with:
          master1-port: 5000
          master2-port: 5001
          master3-port: 5002
          slave1-port: 5003
          slave2-port: 5004
          slave3-port: 5005

      - name: Test
        uses: ./.github/actions/test
        id: cluster
        with:
          cluster-mode: true
          go-version: ${{ inputs.go-version }}
